import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { useTimezone } from '../context/TimezoneContext'
import DropDownTimezone from '../components/DropDownTimezone'
import { RiTimeLine } from 'react-icons/ri'
import Events from '../components/event/Events'
import BuyMeACoffee from '../components/banner/BuyMeACoffee'
import Hero from '../components/Hero'

const Home = () => {
  const { setLocalTime } = useTimezone()

  return (
    <>
      <Head>
        <title>Rise of Empires</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-6xl px-4 mx-auto">
        <Hero />
        <div className="flex my-24">
          <div className="flex flex-wrap w-full justify-between border border-primary-500 bg-primary-200 rounded p-4 md:space-x-1">
            <DropDownTimezone />
            <button
              onClick={setLocalTime}
              className="bg-gradient-to-b from-primary-500 to-primary-600 text-lg hover:to-primary-400 text-white tracking-tight font-bold rounded inline-flex justify-center items-center px-6 py-2 hover:shadow-md mt-2 md:mt-0"
              type="button"
            >
              <RiTimeLine className="mr-2" size={20} /> LOCAL TIMEZONE
            </button>
          </div>
        </div>

        <BuyMeACoffee />

        <Events />
      </div>
    </>
  )
}

export default Home
