import React from 'react'
import Head from 'next/head'
import { useTimezone } from '../context/TimezoneContext'
import DropDownTimezone from '../components/DropDownTimezone'
import { RiTimeLine } from 'react-icons/ri'
import Events from '../components/event/Events'
import { DateTime } from 'luxon'

const Home = () => {
  const { setLocalTime, getCurrentEvent } = useTimezone()

  return (
    <>
      <Head>
        <title>Rise of Empires</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper">
        <div className="row">
          <div className="md-col-8">
            <h1 className="font--size-super txt--black">Rise of Empires</h1>
            <DropDownTimezone className="mb-5" />
            <button onClick={setLocalTime} className="btn btn--blue-600 btn--blue-700:hover focus--blue-700" type="button">
              <RiTimeLine className="mr-2" size={22} /> LOCAL TIMEZONE
            </button>
          </div>
        </div>

        <div className="row">
          <div className="md-col-12">
            <Events />
          </div>
        </div>
      </div>
    </>
  )
}

export default Home
